---
services:
  app:
    build: .
    image: cheat.sh
    container_name: chtsh
    depends_on:
      - redis
    environment:
      - CHEATSH_CACHE_REDIS_HOST=redis
      - CHEATSH_PATH_INTERNAL_BIN_UPSTREAM_RUNNER=/app/.venv/bin/python
    ports:
      - "8002:8002"
    volumes:
      # Or move .venv somewhere and bind . to /app
      - ./bin:/app/bin:Z
      - ./etc:/app/etc:Z
      - ./lib:/app/lib:Z
      - ./share:/app/share:Z
  redis:
    image: redis:8-alpine
    volumes:
      - redis_data:/data
volumes:
  redis_data:
